name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_SECRET }}
          filename: metrics.top.svg
          config_twemoji: yes
          config_padding: 5, 8 + 11%
          use_prebuilt_image: yes
          config_display: column
          template: terminal
          
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_SECRET }}
          filename: metrics.left.svg
          config_twemoji: yes
          config_padding: 5, 8 + 11%
          use_prebuilt_image: yes
          config_display: column
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga             # Display both animes and mangas
          plugin_anilist_sections: watching  # Display only favorites and characters sections
          plugin_anilist_limit: 2                         # Limit to 2 entry per section (characters section excluded)
          plugin_anilist_shuffle: yes                     # Shuffle data for more varied outputs
          plugin_anilist_user: .user.login

      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_SECRET }}
          filename: metrics.right.svg
          config_twemoji: yes
          config_padding: 5, 8 + 11%
          use_prebuilt_image: yes
          config_display: column
          plugin_music: yes
          plugin_music_provider: spotify # Use Spotify as provider
          plugin_music_mode: recent      # Set plugin mode
          plugin_music_limit: 4          # Limit to 4 entries
          plugin_music_played_at: yes    # Show timestamp (for spotify only)
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_SECRET }}
          filename: metrics.bottom.svg
          config_twemoji: yes
          config_padding: 5, 8 + 11%
          use_prebuilt_image: yes
          config_display: column
          plugin_isocalendar: yes
          plugin_stars: yes
          plugin_stars_limit: 4


